[package]
name = "micromacros"
version = "0.1.0"
edition = "2021"

[dependencies]
dbmodel = { path = "./dbmodel/" }
iterable = { path = "./iterable/" }
iterable-trait = { path = "./iterable-trait/" }
